pipeline:
  build:
    image: ensime/ensime:v2.x-cache
    pull: true
    commands:
      - host `curl -s http://httpbin.org/ip | jq -r '.origin'` || true ;
      - git log | head -n 20 ; git fetch -q --tags
      - cask pkg-file ;
        cask install ;
        cask package ;
      - cask exec ert-runner ;
      - cask exec ecukes ;
      # Integration tests are currently unmaintained
      # - cd test/example ; sbt ensimeConfig ; cd ../.. ;
      # - test/run_emacs_tests.sh || test/run_emacs_tests.sh ;
