language: emacs-lisp
env:
  matrix:
    - EMACS_VERSION=emacs-24.3-travis
    - EMACS_VERSION=emacs-24.4-travis
    - EMACS_VERSION=emacs-24.5-travis
    - EMACS_VERSION=emacs-25.1-travis
    - EMACS_VERSION=emacs-25.2-travis
    - EMACS_VERSION=emacs-25.3-travis
    - EMACS_VERSION=emacs-git-snapshot-travis
matrix:
  allow_failures:
  - env: EMACS_VERSION=emacs-git-snapshot-travis

before_install:
  - export PATH="/home/travis/.evm/bin:$PATH"
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - evm config path /tmp
  - evm install $EMACS_VERSION --use || true

script:
  # Make sure the exact emacs version can be found in the build output.
  - emacs -Q --batch --eval '(message (emacs-version))'
  - make test
